### ISSUE TITLE
record-wear contains not classes

### ISSUE THREAD

**Issue by Aeyzaz** [ibm-wearables-sdk-for-mobile/ibm-wearables-android-sdk#2]
record-wear app contains no classes and android studio is unable to install the apk to wear

**Comment by cirilla** [comment]
Hi, the record wear has dependancy to mobileedge-wear module which has a service classes.
Can you please give more details about "android studio is unable to install the apk to wear"

Thanks

**Comment by zachkont** [comment]
Hi, what I think Aeyzaz means is the same issue I'm having: Android studio pops up a "Error running record-wear: Default Activity not found" message whenever I try to run the record-wear module. 

The dependency to mobileegde-wear module is there, but it doesn't work. Could the manifest be wrong? Or is it an android studio bug?

**Comment by OmerArad** [comment]
That's OK. You can ignore this message.
That's a compiler warning that the service you just installed on the Android Wear does not have a "UI" (and it should not have) :)

**Comment by zachkont** [comment]
Yeah but it doesn't run, it's not just a message. It blocks the debug-run of the module
