### ISSUE TITLE
Not actually an issue but need some information.

### ISSUE THREAD

**Issue by Aeyzaz** [ibm-wearables-sdk-for-mobile/ibm-wearables-android-sdk#3]
is is must to send the Sensor data to cloud for train algorithm like you are doing in Record App? Or is there any way i can do this offline without the cloud server?

Thanks!

**Comment by cirilla** [comment]
You must send the data to cloud exactly like in Record App, there is no option to run the train algorithm offline.

Thanks

**Comment by Aeyzaz** [comment]
Thankyou
